# black
[tool.black]
include = 'src\/.*\.pyi?$'
extend-exclude = '''
/migrations/.*.py
'''

# mypy

[tool.mypy]
strict_optional = true
ignore_missing_imports = true
follow_imports = "normal"
show_column_numbers = true

files = ["src"]

plugins = ["mypy_django_plugin.main", "pydantic.mypy"]

[tool.pytest.ini_options]
addopts = "--disable-warnings --durations=20"
DJANGO_SETTINGS_MODULE = "skeleton.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
python_paths = ["lib", "src"]
norecursedirs = ["lib"]